export const SET_SEARCH_QUERY = 'SET_SEARCH_QUERY';
export const SET_LIST_OPTIONS = 'SET_LIST_OPTIONS';
export const ADD_TO_HISTORY = 'ADD_TO_HISTORY';
export const REMOVE_FROM_HISTORY = 'REMOVE_FROM_HISTORY';
export const CLEAR_HISTORY = 'CLEAR_HISTORY';
export const SET_LOADING = 'SET_LOADING';
